[package]
name = "mainline"
version = "1.5.0"
authors = ["nuh.dev"]
edition = "2018"
description = "Simple, robust, BitTorrent's Mainline DHT implementation"
homepage = "https://github.com/nuhvi/mainline"
license = "MIT"
keywords = ["bittorrent", "torrent", "dht", "kademlia", "mainline"]
categories = ["network-programming"]
repository = "https://github.com/nuhvi/mainline"

[dependencies]
rand = "0.8.5"
serde_bencode = "^0.2.4"
serde = { version = "1.0.133", features = ["derive"] }
serde_bytes = "0.11.5"
thiserror = "1.0.49"
crc = "3.0.1"
sha1_smol = "1.0.0"
flume = { version = "0.11.0", features = ["select", "eventual-fairness"], default-features = false }
ed25519-dalek = "2.1.0"
bytes = "1.5.0"
tracing = "0.1"
lru = { version = "0.12.2", default-features = false }

[dev-dependencies]
clap = { version = "4.4.8", features = ["derive"] }
futures = "0.3.29"
tracing-subscriber = "0.3"

[features]
async = ["flume/async"]
default = ["async"]

[[example]]
name = "async_put_mutable"
path = "examples/async/put_mutable.rs"
required-features = ["async"]

[[example]]
name = "async_get_immutable"
path = "examples/async/get_immutable.rs"
required-features = ["async"]
