[package]
name = "mainline"
version = "4.1.0"
authors = ["nuh.dev"]
edition = "2018"
description = "Simple, robust, BitTorrent's Mainline DHT implementation"
homepage = "https://github.com/pubky/mainline"
license = "MIT"
keywords = ["bittorrent", "torrent", "dht", "kademlia", "mainline"]
categories = ["network-programming"]
repository = "https://github.com/pubky/mainline"
resolver = "2"

[dependencies]
rand = "0.8.5"
serde_bencode = "^0.2.4"
serde = { version = "1.0.215", features = ["derive"] }
serde_bytes = "0.11.15"
thiserror = "2.0.3"
crc = "3.2.1"
sha1_smol = "1.0.1"
flume = { version = "0.11.1", features = [], default-features = false }
ed25519-dalek = "2.1.1"
bytes = "1.9.0"
tracing = "0.1"
lru = { version = "0.12.5", default-features = false }
document-features = "0.2.10"
getrandom = { version = "0.2", features = [ "js" ], optional = true }

[dev-dependencies]
clap = { version = "4.5.21", features = ["derive"] }
futures = "0.3.31"
tracing-subscriber = "0.3"
ctrlc = "3.4.5"
histo = "1.0.0"
rayon = "1.10"
dashmap = "6.1"

[features]
## Enable [Dht::as_async()] to use [async_dht::AsyncDht]
async = ["flume/async"]
js = ["getrandom"]

default = []

[package.metadata.docs.rs]
all-features = true

[lints.clippy]
unwrap_used = "deny"
